//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_exam
    {
        public int class_id { get; set; }
        public int exam_id { get; set; }
        public System.DateTime exam_date { get; set; }
        public string max_marks { get; set; }
        public Nullable<int> grade_id { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual exam exam { get; set; }
    }
}
