//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        public int grade_id { get; set; }
        public string min_marks { get; set; }
        public string max_marks { get; set; }
        public string GPA { get; set; }
    }
}
