//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProjectdbEntities1 : DbContext
    {
        public ProjectdbEntities1()
            : base("name=ProjectdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<@class> classes { get; set; }
        public virtual DbSet<class_exam> class_exam { get; set; }
        public virtual DbSet<exam> exams { get; set; }
        public virtual DbSet<exam_result> exam_result { get; set; }
        public virtual DbSet<grade> grades { get; set; }
        public virtual DbSet<std_class> std_class { get; set; }
        public virtual DbSet<std_infor> std_infor { get; set; }
    
        public virtual ObjectResult<showresut_Result> showresut(Nullable<int> std_id, Nullable<int> class_id)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            var class_idParameter = class_id.HasValue ?
                new ObjectParameter("class_id", class_id) :
                new ObjectParameter("class_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showresut_Result>("showresut", std_idParameter, class_idParameter);
        }
    }
}
