//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class std_class
    {
        public int std_id { get; set; }
        public int class_id { get; set; }
        public System.DateTime reg_date { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual std_infor std_infor { get; set; }
    }
}
