//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentResult
    {
        public string std_name { get; set; }
        public int std_id { get; set; }
        public int exam_id { get; set; }
        public int class_id { get; set; }
        public string marks_obt { get; set; }
        public string course_name { get; set; }
        public System.DateTime reg_date { get; set; }
        public System.DateTime att_date { get; set; }
        public string att_status { get; set; }
    }
}
