//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class teacherEntities1 : DbContext
    {
        public teacherEntities1()
            : base("name=teacherEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<facontact> facontacts { get; set; }
        public virtual DbSet<faculty> faculties { get; set; }
    
        public virtual ObjectResult<showt_Result1> showt()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showt_Result1>("showt");
        }
    }
}
